<?php

namespace App\Services;

use App\Models\AnalyticsReport;

class SimplePdfReportService
{
    private array $pages = [];
    private array $current = [];
    private float $y = 750;

    public function render(array $data, AnalyticsReport $report): string
    {
        $this->pages = [];
        $this->current = [];
        $this->y = 750;

        $this->text('PLINK', 20, true);
        $this->text('Recycling Sustainability & Predictive Analytics Report', 16, true);
        $this->text(sprintf(
            'Reporting period: %s to %s',
            $data['range']['from'],
            $data['range']['to']
        ), 10);
        $this->text('Report ID: ' . $report->analytics_report_id, 9);
        $this->gap(8);

        $this->heading('Executive Summary');
        $summary = $data['summary'];
        $this->row('Total recyclable items', $summary['total_items']);
        $this->row('Participating students', $summary['participating_students']);
        $this->row('Points awarded', $summary['total_points']);
        $this->row('Rewards redeemed', $summary['rewards_redeemed']);
        $this->row('Completed recycling transactions', $summary['transactions']);

        $this->heading('Recyclable Type Breakdown');
        if (empty($data['waste_types'])) {
            $this->text('No accepted recyclable items were recorded in this period.', 10);
        } else {
            foreach ($data['waste_types'] as $item) {
                $this->row($item['label'], $item['total_items'] . ' items');
            }
        }

        $this->heading('Top 5 Recyclers');
        if (empty($data['top_recyclers'])) {
            $this->text('No participating recyclers were recorded in this period.', 10);
        } else {
            foreach ($data['top_recyclers'] as $index => $student) {
                $this->text(sprintf(
                    '%d. %s - %d points, %d items',
                    $index + 1,
                    $student['name'],
                    $student['points_earned'],
                    $student['items_recycled']
                ), 10);
            }
        }

        $this->heading('Section Performance');
        foreach (array_slice($data['section_performance'], 0, 5) as $section) {
            $this->text(sprintf(
                '%s - %d items, %d participants, %d points',
                $section['name'],
                $section['total_items'],
                $section['participants'],
                $section['total_points']
            ), 10);
        }

        $this->heading('Current Smart Bin Compartment Status');
        foreach ($data['compartments']['current'] as $compartment) {
            $this->text(sprintf(
                '%s - %d%% full%s',
                $compartment['name'],
                $compartment['fill_percentage'],
                $compartment['distance_cm'] !== null ? ', ' . $compartment['distance_cm'] . ' cm' : ''
            ), 10);
        }

        $this->heading('Prophet Predictive Analytics');
        foreach ($data['predictive'] as $forecast) {
            $this->text($forecast['title'], 11, true);

            if (empty($forecast['forecast'])) {
                $this->text('No stored Prophet forecast is available. Run the forecast from Reports & Analytics first.', 9);
                continue;
            }

            if ($forecast['next_7_total'] !== null) {
                $this->text(
                    'Next 7-day forecast total: ' . $forecast['next_7_total'] . ' ' . $forecast['unit'],
                    9
                );
            }

            if ($forecast['peak_forecast'] !== null) {
                $this->text(
                    'Forecast peak: ' . round($forecast['peak_forecast'], 1) . $forecast['unit'],
                    9
                );
            }

            foreach (array_slice($forecast['forecast'], 0, 7) as $point) {
                $interval = '';
                if ($point['yhat_lower'] !== null && $point['yhat_upper'] !== null) {
                    $interval = sprintf(' (range %.1f-%.1f)', $point['yhat_lower'], $point['yhat_upper']);
                }
                $this->text(sprintf(
                    '%s: %.1f %s%s',
                    $point['ds'],
                    $point['yhat'],
                    $forecast['unit'],
                    $interval
                ), 9);
            }
        }

        $this->gap(8);
        $this->text('Generated by PLINK Reports & Analytics.', 8);
        $this->finishPage();

        return $this->buildPdf();
    }

    private function heading(string $text): void
    {
        $this->gap(10);
        $this->text($text, 13, true);
        $this->gap(3);
    }

    private function row(string $label, string|int|float $value): void
    {
        $this->text($label . ': ' . $value, 10);
    }

    private function gap(float $points): void
    {
        $this->y -= $points;
        $this->ensureSpace(24);
    }

    private function text(string $text, float $size = 10, bool $bold = false): void
    {
        $maxChars = max(30, (int) floor(88 * (10 / max($size, 1))));
        $lines = $this->wrap($text, $maxChars);
        foreach ($lines as $line) {
            $this->ensureSpace($size + 8);
            $font = $bold ? 'F2' : 'F1';
            $escaped = $this->escape($line);
            $this->current[] = sprintf(
                "BT /%s %.1f Tf 54 %.1f Td (%s) Tj ET",
                $font,
                $size,
                $this->y,
                $escaped
            );
            $this->y -= $size + 5;
        }
    }

    private function ensureSpace(float $needed): void
    {
        if ($this->y - $needed < 45) {
            $this->finishPage();
            $this->y = 750;
        }
    }

    private function finishPage(): void
    {
        if ($this->current) {
            $this->pages[] = implode("\n", $this->current);
            $this->current = [];
        }
    }

    private function wrap(string $text, int $maxChars): array
    {
        $wrapped = wordwrap(trim(preg_replace('/\s+/', ' ', $text)), $maxChars, "\n", true);
        return explode("\n", $wrapped ?: '');
    }

    private function escape(string $text): string
    {
        $text = str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $text);
        return preg_replace('/[^\x20-\x7E]/', '-', $text) ?? $text;
    }

    private function buildPdf(): string
    {
        $objects = [];
        $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';

        $fontNormalId = 3;
        $fontBoldId = 4;
        $objects[$fontNormalId] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
        $objects[$fontBoldId] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';

        $pageIds = [];
        $nextId = 5;
        foreach ($this->pages as $content) {
            $pageId = $nextId++;
            $contentId = $nextId++;
            $pageIds[] = $pageId;

            $stream = $content . "\n";
            $objects[$contentId] = "<< /Length " . strlen($stream) . " >>\nstream\n" . $stream . "endstream";
            $objects[$pageId] = sprintf(
                '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 %d 0 R /F2 %d 0 R >> >> /Contents %d 0 R >>',
                $fontNormalId,
                $fontBoldId,
                $contentId
            );
        }

        $kids = implode(' ', array_map(fn ($id) => $id . ' 0 R', $pageIds));
        $objects[2] = sprintf('<< /Type /Pages /Kids [%s] /Count %d >>', $kids, count($pageIds));
        ksort($objects);

        $pdf = "%PDF-1.4\n";
        $offsets = [0 => 0];
        foreach ($objects as $id => $object) {
            $offsets[$id] = strlen($pdf);
            $pdf .= $id . " 0 obj\n" . $object . "\nendobj\n";
        }

        $xref = strlen($pdf);
        $maxId = max(array_keys($objects));
        $pdf .= "xref\n0 " . ($maxId + 1) . "\n";
        $pdf .= "0000000000 65535 f \n";
        for ($id = 1; $id <= $maxId; $id++) {
            $offset = $offsets[$id] ?? 0;
            $pdf .= sprintf('%010d 00000 n ', $offset) . "\n";
        }

        $pdf .= "trailer\n<< /Size " . ($maxId + 1) . " /Root 1 0 R >>\n";
        $pdf .= "startxref\n" . $xref . "\n%%EOF";

        return $pdf;
    }
}
